DROP TABLE IF EXISTS MOVIE_RATING;
DROP VIEW IF EXISTS MOVIE_RATING;
CREATE VIEW MOVIE_RATING
AS
SELECT m.id AS id, IFNULL (AVG(stars), 0) AS rating
    FROM REVIEWS r JOIN MOVIES m
    ON r.movie_id = m.id
    GROUP BY m.id;